name: Split Package

on:
  push:
    branches:
      - master
    paths:
      - 'packages/core/**'

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Split Repository
        run: |
          git subtree split --prefix=packages/core -b split-branch

      - name: Clone and push to target repository
        env:
          GH_TOKEN: ${{ secrets.COMET_TOKEN }}
        run: |
          mkdir -p /tmp/split-repo
          cd /tmp/split-repo
          git init
          git pull $GITHUB_WORKSPACE split-branch
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote add origin "https://${GH_TOKEN}@github.com/doubleedesign/comet-components-core.git"
          git push -u origin master --force
