name: Split Comet Canvas Package

on:
  push:
    branches:
      - master
    paths:
      - 'packages/comet-canvas/**'

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Split Repository
        run: |
          git subtree split --prefix=packages/comet-canvas -b split-branch

      - name: Clone split branch to temp directory
        run: |
          mkdir -p /tmp/split-repo
          cd /tmp/split-repo
          git init
          git pull $GITHUB_WORKSPACE split-branch
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Push to target repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.COMET_TOKEN }}
          branch: master
          force: true
          directory: /tmp/split-repo
          repository: doubleedesign/comet-canvas
